### ISSUE TITLE
Release v0.3.0 Planning

### ISSUE THREAD

**Issue by Billy99** [bpfd-dev/bpfd#669]
This issue tracks the set of issues that need to be completed and included in the v0.3.0 Release (changes since v0.2.0 on May, 21, 2023):

Features:

- [x] #663 
- [x] #670
- [x] #580 
- [x] #614
- [x] #630 
   - [x] #737
- [x] #635
- [x] #658: Includes "aya: allow unsupported maps"
- [x] #521
   - [x] #600: API Change
   - [x] #628: API Change
   - [x] #757
- [x] #429
   - [x] #581: API Change
- [x] #320
   - [x] #570: API Change
   - [x] #605
- [x] #369 & #564
   - [x] #556: API Change
   - [x] #572: API Change
   - [x] #616: API Change
- [x] #459 & #324
   - [x] Fixed by #529: API Change
- [x] #394
   - [x] Fixed by by #541
- [x] #533
   - [x] Partial Fix by #539
   - [x] Partial Fix by #555 
- [x] #514
   - [x] Fixed by #515 Includes "Move bpfd images to use tag :latest instead of :main"
- [x] #339 
   - [x] Fixed by #342: API Change
- [x] #725
   - [x] #736 
- [x] Bump to Aya:main + release bpfd crate
- [ ] Update OLM bundle automatically
- [x] Update Kustomize Release directory for examples (add node to `RELEASE.md`)

Bugs:

- [x] #666 
   - [x] Fixed by #667
- [x] #640 
   - [x] Fixed by #649 
- [x] #638 Includes "change kind deployment to a single node"
- [x] #613: API Change
- [x] #612
- [x] #500 
   - [x] Fixed by #523
- [x] #733

**Comment by astoycos** [comment]
TODO @astoycos Track in Milestone?

**Comment by astoycos** [comment]
Done in #770
